image: Visual Studio 2019

install:
- ps: |
    $env:COMM_TAG = $(git describe --always --dirty="(X)")
    $env:PROJECT = "FontLoaderSub"
    $env:CMDLINE_DEFINE = "FONTLOADERSUB_GIT_VERSION=\""{0}\""" -f $env:COMM_TAG

build_script:
- msbuild /p:Platform=x86 /p:Configuration=Minimize

after_build:
- ps: |
    $CONFIGS = @(
        "Minimize";
    )
    foreach ($conf in $CONFIGS) {
        7z a "$env:PROJECT-$env:COMM_TAG-$conf.zip" "$conf\" "-xr!*.iobj" "-xr!*.ipdb"
    }

    Get-ChildItem . -Recurse | where {$_.Extension -eq ".exe"} | Get-FileHash -Algorithm SHA256

artifacts:
- path: '*.zip'
